version: "3.6"
services:
  web:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - backend
    ports:
      - "80:80"
  redis:
    image: redis
    networks:
      - backend

networks:
  backend:
